---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: secretsManager
  region: eu-central-1
  data:
    - key: hello-service/password
      name: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-version-1
  annotations:
    secret.reloader.stakater.com/reload: "hello-service"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0           #  3 20 30s - 100% 1min down 1000
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      name: web
      labels:
        role: webserver
    spec:
      containers:
      - name: web
        image: jjino/web-app:v1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: BACKEND_USERNAME
          valueFrom:
            secretKeyRef:
              name: hello-service
              key: password